[tool.poetry]
name = "saw-client"
version = "0.9.0"
readme = "README.md"
description = "SAW client for the SAW 0.9 RPC server"
authors = ["Galois, Inc. <saw@galois.com>"]
license = "BSD License"
include = [
    "LICENSE",
    "mypy.ini",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
BitVector = "^3.4.9"
cryptol = "2.12.0" # { path = "../../deps/cryptol/cryptol-remote-api/python/", develop = true }
argo-client = "~0.0.6"

[tool.poetry.dev-dependencies]
mypy = "^0.812"

[build-system]
requires = ["poetry>=1.1.4", "setuptools>=40.8.0"]
